manage tokens
coopengo/trytond-api-token pull request #1
Opened 2018-02-13 16:58 UTC by alikefia

2018-02-13 17:11 UTC, fredericlangevin requested changes

2018-02-13 17:11 UTC, fredericlangevin commented on tryton.cfg
> +version=4.4.0
4.5.0

2018-02-13 17:11 UTC, fredericlangevin commented on locale/fr.po
> +msgstr "Content-Type: text/plain; charset=utf-8\n"
il est bien vide :)

2018-02-13 17:11 UTC, fredericlangevin commented on token.py
> +    user = fields.Many2One('res.user', 'User', required=True)
pourquoi user?

2018-02-13 17:11 UTC, fredericlangevin commented on token.py
> +    user = fields.Many2One('res.user', 'User', required=True)
readonly non?

2018-02-13 17:11 UTC, fredericlangevin commented on token.py
> +    party = fields.Many2One('party.party', 'Party')
readonly?

2018-02-14 09:26 UTC, alikefia commented on locale/fr.po
> +msgstr "Content-Type: text/plain; charset=utf-8\n"
ha bon?

2018-02-14 09:27 UTC, alikefia commented on token.py
> +    user = fields.Many2One('res.user', 'User', required=True)
J'aurai préféré un profile mais tryton a besoin d'un user qui call un RPC (rien que pour modified_uid)
Au fait ce user va définir les authorization au sens de trytond
la party va limiter ces droits en termes de périmètre de données
Cas d'utilisation type: site B2C

2018-02-14 09:27 UTC, alikefia commented on token.py
> +    user = fields.Many2One('res.user', 'User', required=True)
Il faut bien le set

2018-02-14 09:27 UTC, alikefia commented on token.py
> +    party = fields.Many2One('party.party', 'Party')
idem

2018-02-20 11:05 UTC, fredericlangevin approved these changes

2018-02-20 11:05 UTC, fredericlangevin commented on token.py
> +    active = fields.Boolean('Active')
j'ajouterai un name

2018-02-20 15:33 UTC, merged